import type { Document } from './types';
import React from 'react';

// NOTE: id and createdAt will be generated by Firestore
export const MOCK_DOCUMENTS: Omit<Document, 'id' | 'createdAt'>[] = [
  {
    title: 'The School-to-Prison Pipeline: Structuring Legal Reform',
    authors: ['Catherine Y. Kim', 'Daniel J. Losen', 'Damon T. Hewitt'],
    year: 2010,
    summary: 'An examination of the policies and practices that push students, particularly those from disadvantaged backgrounds, out of schools and into the justice system.',
    simplifiedSummary: 'This document looks at how school rules and policies can unintentionally lead students, especially those from underprivileged backgrounds, into the criminal justice system. It discusses ways to change these legal structures to prevent this.',
    resourceType: 'Book Chapter',
    subjects: ['legal reform', 'policy', 'racial disparity'],
    publicationTitle: 'Ending the School-to-Prison Pipeline',
    pdfUrl: 'https://www.pacer.org/bullying/resources/info-facts/school-to-prison-pipeline.pdf',
    interventions: ['legal reform', 'policy changes'],
    keyPopulations: ['students from disadvantaged backgrounds', 'students of color'],
    riskFactors: ['punitive school policies', 'racial disparity'],
    keyStats: [
        'Students of color are 3.5 times more likely to be suspended than white students.',
        'Schools with zero-tolerance policies have higher rates of expulsion for minor infractions.',
        'A 10% increase in graduation rates corresponds to a 9% decline in criminal arrest rates.'
    ],
    keyOrganizations: ['Charles Hamilton Houston Institute']
  },
  {
    title: 'Zero Tolerance, High Stakes, and the School-to-Prison Pipeline',
    authors: ['Russell J. Skiba'],
    year: 2012,
    summary: 'This paper explores the impact of zero tolerance policies in schools and their contribution to increased suspension, expulsion, and referral to law enforcement.',
    simplifiedSummary: "This paper examines 'zero tolerance' rules in schools. It argues that these strict policies lead to more students being suspended, expelled, or reported to the police, effectively pushing them towards the justice system.",
    resourceType: 'Journal Article',
    subjects: ['zero tolerance', 'suspension', 'expulsion'],
    publicationTitle: 'Educational Researcher',
    pdfUrl: 'https://www.dignityinschools.org/wp-content/uploads/2021/10/A-VI-for-All-Digital-Report-092121.pdf',
    interventions: ['policy analysis'],
    keyPopulations: ['general student population'],
    riskFactors: ['zero tolerance policies', 'suspension', 'expulsion'],
    keyStats: [
        'Over 95% of out-of-school suspensions are for nonviolent, minor disruptions such as tardiness or dress code violations.',
        'Schools with higher suspension rates do not have better academic outcomes.',
    ],
    keyOrganizations: []
  },
  {
    title: 'Race, Disability, and the School-to-Prison Pipeline',
    authors: ['Thalia N.C. Gonzalez'],
    year: 2017,
    summary: 'Analyzes the disproportionate impact of disciplinary policies on students of color and students with disabilities, highlighting the intersectionality of race and disability.',
    simplifiedSummary: 'This research focuses on how school discipline rules unfairly affect students of color and those with disabilities. It shows that these students are more likely to be punished, which is a key part of the school-to-prison pipeline.',
    resourceType: 'Journal Article',
    subjects: ['racial disparity', 'disability', 'intersectionality'],
    publicationTitle: 'The Journal of Law & Equity',
    pdfUrl: 'https://advancementproject.org/wp-content/uploads/2017/02/WeCameToLearn.pdf',
    interventions: ['disciplinary policy reform'],
    keyPopulations: ['students of color', 'students with disabilities', 'ADHD'],
    riskFactors: ['racial disparity', 'disability discrimination', 'intersectionality'],
    keyStats: [
        'Black students represent 16% of student enrollment but 31% of school-related arrests.',
        'Students with disabilities are twice as likely to receive an out-of-school suspension than students without disabilities.',
    ],
    keyOrganizations: []
  },
  {
    title: 'Dismantling the School-to-Prison Pipeline: A Restorative Justice Approach',
    authors: ['The Advancement Project'],
    year: 2014,
    summary: 'Advocates for the use of restorative justice practices as an alternative to punitive disciplinary measures to build community and reduce conflict in schools.',
    simplifiedSummary: "This report proposes using 'restorative justice' in schools instead of harsh punishments. This approach focuses on repairing harm and building community to solve conflicts, aiming to break the cycle of the school-to-prison pipeline.",
    resourceType: 'Report',
    subjects: ['restorative justice', 'alternative discipline', 'community building'],
    publicationTitle: 'Advancement Project Reports',
    pdfUrl: 'https://advancementproject.org/wp-content/uploads/2017/02/Restorative-Justice-Toolkit-for-Educators.pdf',
    interventions: ['restorative justice'],
    keyPopulations: ['school communities'],
    riskFactors: ['punitive disciplinary measures', 'school conflict'],
    keyStats: [
        'Schools using restorative justice have seen suspension rates drop by as much as 40%.',
        'Restorative practices can improve school climate and teacher-student relationships.',
    ],
    keyOrganizations: ['The Advancement Project']
  }
];

export const Logo: React.FC<{ className?: string }> = ({ className }) => (
    <div className={`flex items-center gap-3 ${className}`}>
        <div className="w-10 h-10 flex-shrink-0">
            <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                <path className="fill-brand-primary dark:fill-white" d="M81.2,59.3c0-9.8-12.8-17.8-28.5-17.8s-28.5,8-28.5,17.8c0,2.1,0.6,4.1,1.7,6h53.6C80.6,63.4,81.2,61.4,81.2,59.3z M52.7,4.8C42.4,4.8,34,13.2,34,23.5s8.4,18.7,18.7,18.7s18.7-8.4,18.7-18.7S63,4.8,52.7,4.8z M52.7,60.5 c-20.9,0-37.8,12-37.8,26.8v10.5h75.6V87.3C90.5,72.5,73.6,60.5,52.7,60.5z" />
                <rect x="44" y="10" width="5" height="70" className="fill-base-100 dark:fill-dark-base-300" />
                <rect x="52" y="10" width="5" height="70" className="fill-base-100 dark:fill-dark-base-300" />
                <rect x="60" y="10" width="5" height="70" className="fill-base-100 dark:fill-dark-base-300" />
            </svg>
        </div>
        <span className="hidden sm:inline text-xl font-bold tracking-tight text-slate-800 dark:text-slate-100 whitespace-nowrap">
            School-to-Prison Pipeline Evidence Project
        </span>
    </div>
);

export const SearchIcon: React.FC<{className?: string}> = ({ className = "h-6 w-6" }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
  </svg>
);

export const UploadIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5m-13.5-9L12 3m0 0 4.5 4.5M12 3v13.5" />
  </svg>
);

export const DocumentIcon: React.FC<{className?: string}> = ({ className = "h-8 w-8" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
    </svg>
);

export const CloseIcon: React.FC<{className?: string}> = ({ className = "h-6 w-6" }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
  </svg>
);

export const LoadingSpinner: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg className={`animate-spin ${className}`} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
);

export const CheckCircleIcon: React.FC<{className?: string}> = ({ className = "h-6 w-6" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>
);

export const TrashIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.124-2.033-2.124H8.033c-1.12 0-2.033.944-2.033 2.124v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
  </svg>
);

export const AdminIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
    </svg>
);

export const BookmarkIcon: React.FC<{className?: string, isSaved?: boolean}> = ({ className = "h-5 w-5", isSaved }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill={isSaved ? "currentColor" : "none"} viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.5 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z" />
    </svg>
);

export const CiteIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 7.5V6.108c0-1.135.845-2.098 1.976-2.192.373-.03.748-.03 1.125 0 1.131.094 1.976 1.057 1.976 2.192V7.5M8.25 7.5h7.5M8.25 7.5V15M15.75 7.5V15m-7.5 0h7.5M5.25 9h.008v.008H5.25V9Zm3.75 0h.008v.008H9V9Zm3.75 0h.008v.008H12.75V9Zm3.75 0h.008v.008H16.5V9Zm-12 3.75h.008v.008H4.5v-3.75Zm3.75 0h.008v.008H8.25v-3.75Zm3.75 0h.008v.008H12v-3.75Zm3.75 0h.008v.008H15.75v-3.75Zm3.75 0h.008v.008H19.5v-3.75Z" />
    </svg>
);

export const DownloadIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
    </svg>
);

export const ListIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0ZM3.75 12h.007v.008H3.75V12Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm-.375 5.25h.007v.008H3.75v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
);

export const UserGroupIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M18 18.72a9.094 9.094 0 0 0 3.75-5.25T21 12a9 9 0 0 0-3.75-5.25m0 10.5h0_M12 15.75a3 3 0 0 1-3-3m3 3a3 3 0 0 0 3-3m-3 3V15m-3 0v-1.5m-3.75-9.75a9.094 9.094 0 0 0-3.75 5.25T3 12a9 9 0 0 0 3.75 5.25m-3.75 0h0_M3.75 6.75h0_m0 0a9.094 9.094 0 0 1 3.75-5.25T12 3a9 9 0 0 1 5.25 3.75m0 0h0" />
    </svg>
);

export const LinkIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M13.19 8.688a4.5 4.5 0 0 1 1.242 7.244l-4.5 4.5a4.5 4.5 0 0 1-6.364-6.364l1.757-1.757m13.35-.622 1.757-1.757a4.5 4.5 0 0 0-6.364-6.364l-4.5 4.5a4.5 4.5 0 0 0 1.242 7.244" />
    </svg>
);

export const ChartBarIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" />
    </svg>
);

export const ArrowRightIcon: React.FC<{className?: string}> = ({ className = "h-6 w-6" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
    </svg>
);

export const AcademicCapIcon: React.FC<{className?: string}> = ({ className = "h-8 w-8" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path d="M12 14l9-5-9-5-9 5 9 5z" />
        <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222 4 2.222V20M1 12l5.316 2.953A12.06 12.06 0 0112 15a12.06 12.06 0 015.684-2.047L23 12" />
    </svg>
);

export const ScaleIcon: React.FC<{className?: string}> = ({ className = "h-8 w-8" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v17.25m0 0c-1.472 0-2.882.265-4.185.75M12 20.25c1.472 0 2.882.265 4.185.75M18.75 4.97A48.416 48.416 0 0 0 12 4.5c-2.291 0-4.545.16-6.75.47m13.5 0c1.01.143 2.01.317 3 .52m-3-.52v16.5m-1.5-16.5v16.5m-1.5-16.5v16.5m-1.5-16.5v16.5m-1.5-16.5v16.5m-1.5-16.5v16.5m-9-16.5c-1.01.143-2.01.317-3 .52m3-.52v16.5m1.5-16.5v16.5m1.5-16.5v16.5m1.5-16.5v16.5m1.5-16.5v16.5m1.5-16.5v16.5" />
    </svg>
);

export const BuildingLibraryIcon: React.FC<{className?: string}> = ({ className = "h-8 w-8" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 21v-8.25M15.75 21v-8.25M8.25 21v-8.25M3 9l9-6 9 6m-1.5 12V10.332A48.36 48.36 0 0 0 12 9.75c-2.551 0-5.056.2-7.5.582V21M3 21h18M12 6.75h.008v.008H12V6.75Z" />
    </svg>
);

export const ExclamationTriangleIcon: React.FC<{className?: string}> = ({ className = "h-8 w-8" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
    </svg>
);

export const ChevronDownIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
    </svg>
);

export const EyeIcon: React.FC<{className?: string}> = ({ className = "h-5 w-5" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.432 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
    </svg>
);